package com.faster.festival.domain.sos

/**
 * One partial-details submit for `POST /pinch-alert-details`. Each variant maps
 * to exactly the body keys the Pinch SOS Frontend Endpoint contract specifies —
 * the repository serializes only the present keys (no null padding) so the
 * signed byte string matches the contract.
 *
 * All variants are merged server-side onto the same `alert_id`; each carries a
 * unique `client_update_id` (generated by the caller) for idempotent dedup.
 */
sealed interface PinchAlertDetail {

    /** Short tag used for the `client_update_id` prefix + logs. */
    val kind: String

    /** Phone number staff can call. */
    data class Phone(
        val phoneE164: String,
        val source: String = "user_entered"
    ) : PinchAlertDetail {
        override val kind: String get() = "phone"
    }

    /** Medical conditions (e.g. "severe_allergy", "asthma"). */
    data class Medical(
        val medicalInfo: List<String>
    ) : PinchAlertDetail {
        override val kind: String get() = "medical"
    }

    /** "What happened" — categories + optional severity/notes. */
    data class Incident(
        val categories: List<String>,
        val severityHint: String? = null,
        val additionalNotes: String? = null
    ) : PinchAlertDetail {
        override val kind: String get() = "incident"
    }

    /** "What happened" skipped by the user. */
    data object IncidentDeclined : PinchAlertDetail {
        override val kind: String get() = "incident"
    }

    /** Manual location pick (a predefined festival zone). */
    data class LocationChoice(
        val choice: String,
        val description: String
    ) : PinchAlertDetail {
        override val kind: String get() = "location"
    }
}
