package com.faster.festival.domain.sos

import com.faster.festival.data.sos.DeviceRegistrationManager
import com.faster.festival.data.sos.isSosRetryable
import com.faster.festival.data.sos.remote.SosAlert
import com.faster.festival.data.sos.remote.SosLocation
import com.faster.festival.data.sos.remote.WristbandInfo
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import timber.log.Timber

/**
 * Idempotent device + attestation bootstrap. Run once on app start when
 * membership becomes active.
 */
class RegisterDeviceUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(): DeviceRegistrationManager.BootstrapResult = repo.bootstrap()
}

/**
 * Stand-alone re-verify hook (e.g. user toggles "reset trusted device" in
 * settings). For first-time setup callers should use [RegisterDeviceUseCase].
 */
class VerifyAttestationUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(): DeviceRegistrationManager.BootstrapResult {
        repo.resetTrustedDevice()
        return repo.bootstrap()
    }
}

/**
 * Trigger an SOS event with retry on network / 5xx.
 *
 *  • `clientTriggerId` is generated by the caller (one per SOS tap) and
 *    passed unchanged across retries.
 *  • Each retry generates a fresh nonce + timestamp + body hash + signature
 *    inside [SosRepository.triggerSos].
 */
class TriggerSOSUseCase(private val repo: SosRepository) {

    suspend operator fun invoke(
        clientTriggerId: String,
        festivalId: String,
        location: SosLocation?,
        wristband: WristbandInfo,
        maxAttempts: Int = 3
    ): Result<TriggerHandle> {
        var lastError: Throwable? = null
        for (attempt in 1..maxAttempts) {
            val res = repo.triggerSos(clientTriggerId, festivalId, location, wristband)
            if (res.isSuccess) return res
            val err = res.exceptionOrNull() ?: return res
            lastError = err
            if (!err.isSosRetryable() || attempt == maxAttempts) {
                Timber.tag(TAG).w(
                    err,
                    "pinch-ingest non-retryable / final attempt %d",
                    attempt
                )
                return Result.failure(err)
            }
            // Exponential backoff inside the SOS-ACK-deadline budget:
            //   attempt 1 fail → 500ms → attempt 2
            //   attempt 2 fail → 1500ms → attempt 3 (final)
            val delayMs = 500L * (1L shl (attempt - 1))
            Timber.tag(TAG).i("pinch-ingest retryable failure; backoff %dms", delayMs)
            delay(delayMs)
        }
        return Result.failure(lastError ?: IllegalStateException("SOS retry exhausted"))
    }

    private companion object {
        const val TAG = "TriggerSOSUseCase"
    }
}

/**
 * Polls `pinch-alert-status` per Pinch_SOS_Frontend_Implementation_Guide.md:
 *
 *   • "every 1-2 seconds for the first 30 seconds" → [FAST_INTERVAL_MS] = 1.5s
 *   • "After DISPATCH_RECEIVED, poll every 3-5 seconds" → [SLOW_INTERVAL_MS] = 4s
 *   • Stop on RESOLVED / CLOSED / REJECTED / CANCELLED_BY_USER
 *     ([SosUserStatus.isTerminal])
 *
 * The cadence switch triggers on EITHER condition — whichever happens first:
 *   1. We have observed [SosUserStatus.DispatchReceived] or any later state.
 *   2. 30 seconds have elapsed since polling started (safety fallback for
 *      backends that skip the DISPATCH_RECEIVED transition).
 *
 * Emits each [SosAlert] update as a domain-level event. Cancellation is
 * cooperative — callers should run inside a `viewModelScope` so navigating
 * away tears the loop down naturally.
 */
class PollSOSStatusUseCase(private val repo: SosRepository) {

    /**
     * Polls by [alertId] when known (preferred — the new contract keys status
     * on the alert id), falling back to [clientTriggerId] before the alert id
     * is available (e.g. a re-dispatch still pending).
     */
    operator fun invoke(alertId: String?, clientTriggerId: String?): Flow<SosAlert> = flow {
        val started = System.currentTimeMillis()
        var dispatchReached = false
        var serverCadenceMs: Long? = null
        var serverSaidStop = false
        var consecutiveAuthFailures = 0
        var consecutiveTransientFailures = 0

        while (true) {
            val res = repo.pollStatus(alertId, clientTriggerId)
            res.onSuccess { alert ->
                consecutiveAuthFailures = 0
                consecutiveTransientFailures = 0
                if (alert != null) {
                    emit(alert)
                    val status = SosUserStatus.fromRaw(alert.userStatus)
                    val uiStatus = PinchUiStatus.fromRaw(alert.uiStatus)

                    // Terminal — ui_status is authoritative (COMPLETED / CANCELLED
                    // / REJECTED), with user_status as a back-compat fallback.
                    if (uiStatus.isTerminal || status.isTerminal) {
                        Timber.tag(TAG).i(
                            "Polling terminal — ui=%s user=%s", alert.uiStatus, alert.userStatus
                        )
                        return@flow
                    }

                    // Server-side `polling.continue == false` is an authoritative
                    // stop signal — dispatch may close the case without a
                    // RESOLVED/CLOSED user_status.
                    if (alert.polling?.shouldContinue == false) {
                        Timber.tag(TAG).i("Polling stopped by server (polling.continue=false)")
                        serverSaidStop = true
                        return@onSuccess
                    }

                    // Honor server-driven cadence when present. Falls back
                    // to client-side rules only if backend omits the block.
                    serverCadenceMs = alert.polling?.foregroundIntervalSeconds
                        ?.toLong()
                        ?.times(1_000L)

                    if (!dispatchReached &&
                        status.progressIndex >= SosUserStatus.DispatchReceived.progressIndex
                    ) {
                        dispatchReached = true
                        Timber.tag(TAG).d("Cadence switch — DISPATCH_RECEIVED reached")
                    }
                }
            }.onFailure { err ->
                // TokenRefreshInterceptor already retries 401 once with a
                // refreshed Bearer. If we STILL see 401 here, the refresh
                // failed (e.g. refresh token expired, user fully logged out).
                // Spamming the polling loop after that is pointless — stop.
                val code = (err as? retrofit2.HttpException)?.code()
                when (code) {
                    401, 403 -> {
                        consecutiveAuthFailures++
                        Timber.tag(TAG).w(
                            "Polling auth failure %d/%d — code=%d",
                            consecutiveAuthFailures, MAX_AUTH_FAILURES, code
                        )
                        if (consecutiveAuthFailures >= MAX_AUTH_FAILURES) {
                            Timber.tag(TAG).e(
                                "Polling stopping — token refresh exhausted (HTTP %d)", code
                            )
                            serverSaidStop = true
                            return@onFailure
                        }
                    }
                    else -> {
                        consecutiveTransientFailures++
                        Timber.tag(TAG).w(
                            err, "Polling transient error %d/%d — keeping loop",
                            consecutiveTransientFailures, MAX_TRANSIENT_FAILURES
                        )
                        if (consecutiveTransientFailures >= MAX_TRANSIENT_FAILURES) {
                            Timber.tag(TAG).e(
                                err, "Polling stopping — too many consecutive transient errors"
                            )
                            serverSaidStop = true
                            return@onFailure
                        }
                    }
                }
            }

            if (serverSaidStop) return@flow

            val cadence = serverCadenceMs ?: run {
                val elapsed = System.currentTimeMillis() - started
                val timeFallback = elapsed >= FAST_PHASE_MS
                if (dispatchReached || timeFallback) SLOW_INTERVAL_MS else FAST_INTERVAL_MS
            }
            delay(cadence)
        }
    }

    private companion object {
        const val TAG = "PollSOSStatusUseCase"
        const val FAST_PHASE_MS = 30_000L     // spec safety fallback
        const val FAST_INTERVAL_MS = 1_500L   // 1-2s range
        const val SLOW_INTERVAL_MS = 4_000L   // 3-5s range
        /** Polls allowed before unrecoverable auth failure ends the loop. */
        const val MAX_AUTH_FAILURES = 2
        /** Consecutive transport / 5xx errors before we give up. */
        const val MAX_TRANSIENT_FAILURES = 6
    }
}

/**
 * Submits one signed partial-details update (`pinch-alert-details`). The caller
 * generates the [clientUpdateId] once per user action and reuses it on retry so
 * the backend dedups.
 */
class SubmitPinchDetailsUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(
        alertId: String,
        detail: PinchAlertDetail,
        clientUpdateId: String
    ): Result<Unit> = repo.sendAlertDetails(alertId, detail, clientUpdateId)
}

/**
 * Requests cancellation (`pinch-cancel`, unsigned). Returns the backend
 * `ui_status` (typically CANCEL_REQUESTED). Cancel success is NOT assumed — the
 * caller keeps polling and renders the authoritative ui_status.
 */
class CancelPinchSOSUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(
        alertId: String,
        clientRequestId: String,
        reason: String
    ): Result<PinchUiStatus> = repo.cancelSos(alertId, clientRequestId, reason)
}

/**
 * One signed location push (`pinch-update-location`). Used for the on-demand
 * "My current location" action; the periodic background cadence is driven by
 * [com.faster.festival.core.sos.ActiveSosForegroundService].
 */
class SendLocationUpdateUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(
        clientTriggerId: String,
        trackingSessionId: String,
        location: SosLocation
    ): Result<Unit> = repo.sendLocationUpdate(clientTriggerId, trackingSessionId, location)
}

/**
 * Fetches a page of the user's past SOS alerts (`pinch-alert-history`). Drives
 * the SOS History screen; pass the prior response's `next_cursor` back as
 * [cursor] to page.
 */
class FetchSosHistoryUseCase(private val repo: SosRepository) {
    suspend operator fun invoke(
        limit: Int = 20,
        festivalId: String? = null,
        cursor: String? = null
    ): Result<com.faster.festival.data.sos.remote.PinchAlertHistoryResponse> =
        repo.fetchAlertHistory(limit = limit, festivalId = festivalId, cursor = cursor)
}
